version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.58.0
    resource_class: small
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run build
          command: "cargo build"
      - run:
          name: Run Tests
          command: "cargo test"
      - run:
          name: fmt
          command: "cargo fmt"
